#!/bin/bash

set -e

# Handle termination signals
_term() {
    echo "Received SIGTERM - shutting down Haven relay..."
    kill -TERM "$haven_process" 2>/dev/null
    wait "$haven_process"
    exit 0
}

trap _term TERM INT

# Ensure data directory exists
mkdir -p "$APP_DATA_DIR"

echo "========================================"
echo "Starting Haven Nostr Relay for Start9"
echo "========================================"

# Load Start9 configuration
CONFIG_FILE="$APP_DATA_DIR/start9/config.yaml"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: Configuration file not found at $CONFIG_FILE"
    echo "Please configure Haven through Start9's Config interface"
    exit 1
fi

echo "Loading configuration from Start9..."

# Copy Haven .env file from data volume to /haven directory
# setConfig.ts generates this file when user saves configuration
ENV_SOURCE="$APP_DATA_DIR/start9/haven.env"
ENV_DEST="/haven/.env"

if [ -f "$ENV_SOURCE" ]; then
    echo "Copying configuration from Start9..."
    cp "$ENV_SOURCE" "$ENV_DEST"
else
    echo "WARNING: Haven configuration not found, creating minimal default..."
    cat > "$ENV_DEST" <<EOF
# Minimal Haven configuration generated by entrypoint
OWNER_NPUB="npub1example0000000000000000000000000000000000000000000000000000000000000"
OWNER_USERNAME="Haven"
RELAY_URL="ws://localhost:3355"
RELAY_PORT=3355
RELAY_BIND_ADDRESS="0.0.0.0"
DB_ENGINE="badger"
LMDB_MAPSIZE=273000000000
BLOSSOM_PATH="$APP_DATA_DIR/blossom"
PRIVATE_RELAY_NAME="Private Relay"
PRIVATE_RELAY_NPUB="npub1example0000000000000000000000000000000000000000000000000000000"
PRIVATE_RELAY_DESCRIPTION="A safe place to store drafts"
PRIVATE_RELAY_ICON=""
PRIVATE_RELAY_EVENT_IP_LIMITER_TOKENS_PER_INTERVAL=50
PRIVATE_RELAY_EVENT_IP_LIMITER_INTERVAL=1
PRIVATE_RELAY_EVENT_IP_LIMITER_MAX_TOKENS=100
PRIVATE_RELAY_ALLOW_EMPTY_FILTERS=true
PRIVATE_RELAY_ALLOW_COMPLEX_FILTERS=true
PRIVATE_RELAY_CONNECTION_RATE_LIMITER_TOKENS_PER_INTERVAL=3
PRIVATE_RELAY_CONNECTION_RATE_LIMITER_INTERVAL=5
PRIVATE_RELAY_CONNECTION_RATE_LIMITER_MAX_TOKENS=9
CHAT_RELAY_NAME="Chat Relay"
CHAT_RELAY_NPUB="npub1example0000000000000000000000000000000000000000000000000000000000"
CHAT_RELAY_DESCRIPTION="Private chats"
CHAT_RELAY_ICON=""
CHAT_RELAY_WOT_DEPTH=3
CHAT_RELAY_WOT_REFRESH_INTERVAL_HOURS=24
CHAT_RELAY_MINIMUM_FOLLOWERS=3
CHAT_RELAY_EVENT_IP_LIMITER_TOKENS_PER_INTERVAL=50
CHAT_RELAY_EVENT_IP_LIMITER_INTERVAL=1
CHAT_RELAY_EVENT_IP_LIMITER_MAX_TOKENS=100
CHAT_RELAY_ALLOW_EMPTY_FILTERS=false
CHAT_RELAY_ALLOW_COMPLEX_FILTERS=false
CHAT_RELAY_CONNECTION_RATE_LIMITER_TOKENS_PER_INTERVAL=3
CHAT_RELAY_CONNECTION_RATE_LIMITER_INTERVAL=3
CHAT_RELAY_CONNECTION_RATE_LIMITER_MAX_TOKENS=9
OUTBOX_RELAY_NAME="Outbox Relay"
OUTBOX_RELAY_NPUB="npub1example0000000000000000000000000000000000000000000000000000000"
OUTBOX_RELAY_DESCRIPTION="Public relay"
OUTBOX_RELAY_ICON=""
OUTBOX_RELAY_EVENT_IP_LIMITER_TOKENS_PER_INTERVAL=10
OUTBOX_RELAY_EVENT_IP_LIMITER_INTERVAL=60
OUTBOX_RELAY_EVENT_IP_LIMITER_MAX_TOKENS=100
OUTBOX_RELAY_ALLOW_EMPTY_FILTERS=false
OUTBOX_RELAY_ALLOW_COMPLEX_FILTERS=false
OUTBOX_RELAY_CONNECTION_RATE_LIMITER_TOKENS_PER_INTERVAL=3
OUTBOX_RELAY_CONNECTION_RATE_LIMITER_INTERVAL=1
OUTBOX_RELAY_CONNECTION_RATE_LIMITER_MAX_TOKENS=9
INBOX_RELAY_NAME="Inbox Relay"
INBOX_RELAY_NPUB="npub1example0000000000000000000000000000000000000000000000000000000"
INBOX_RELAY_DESCRIPTION="Interactions"
INBOX_RELAY_ICON=""
INBOX_PULL_INTERVAL_SECONDS=600
INBOX_RELAY_EVENT_IP_LIMITER_TOKENS_PER_INTERVAL=10
INBOX_RELAY_EVENT_IP_LIMITER_INTERVAL=1
INBOX_RELAY_EVENT_IP_LIMITER_MAX_TOKENS=20
INBOX_RELAY_ALLOW_EMPTY_FILTERS=false
INBOX_RELAY_ALLOW_COMPLEX_FILTERS=false
INBOX_RELAY_CONNECTION_RATE_LIMITER_TOKENS_PER_INTERVAL=3
INBOX_RELAY_CONNECTION_RATE_LIMITER_INTERVAL=1
INBOX_RELAY_CONNECTION_RATE_LIMITER_MAX_TOKENS=9
IMPORT_START_DATE="2023-01-20"
IMPORT_QUERY_INTERVAL_SECONDS=600
IMPORT_OWNER_NOTES_FETCH_TIMEOUT_SECONDS=60
IMPORT_TAGGED_NOTES_FETCH_TIMEOUT_SECONDS=120
IMPORT_SEED_RELAYS_FILE="$APP_DATA_DIR/start9/relays_import.json"
BACKUP_PROVIDER="none"
BACKUP_INTERVAL_HOURS=24
BLASTR_RELAYS_FILE="$APP_DATA_DIR/start9/relays_blastr.json"
WOT_FETCH_TIMEOUT_SECONDS=60
HAVEN_LOG_LEVEL="INFO"
TZ="UTC"
EOF
fi

# Export configuration variables for path handling
set -a
# shellcheck disable=SC1090
. "$ENV_DEST"
set +a

# Ensure supporting directories exist and seed relay lists if missing
if [ -n "$BLOSSOM_PATH" ]; then
    mkdir -p "$BLOSSOM_PATH"
fi

for path_var in BLASTR_RELAYS_FILE IMPORT_SEED_RELAYS_FILE; do
    value=$(eval "printf '%s' \"\${$path_var}\"")
    if [ -n "$value" ]; then
        dir_path="$(dirname "$value")"
        mkdir -p "$dir_path"
        if [ ! -f "$value" ]; then
            echo "[]" > "$value"
        fi
    fi
done

echo "Configuration loaded successfully"
echo "Starting Haven relay on port 3355..."
echo "Data directory: $APP_DATA_DIR"
echo "========================================"

# Haven reads .env from current working directory (/haven)
cd /haven
./haven &
haven_process=$!

echo "Haven relay started (PID: $haven_process)"
echo "Waiting for relay to be ready..."

wait $haven_process
