# Reference docker-compose.yml - Haven Relay Service
# This file is for reference only - the actual Dockerfile builds the relay directly

version: "3.7"

services:
  # Haven Nostr Relay
  haven_relay:
    image: letdown2491/haven-relay:latest
    restart: unless-stopped
    ports:
      - "3355:3355"
    volumes:
      - ${APP_DATA_DIR}/data/config:/haven-config
      - ${APP_DATA_DIR}/data/blossom:/haven/blossom
      - ${APP_DATA_DIR}/data/db:/haven/db
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3355"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
